### ISSUE TITLE
Google搜索下的bug

### ISSUE THREAD

**Issue by LisonChan** [holleworldabc/mini-tools#3]
在Mac上把扩展加载到adguard使用时，Google搜索的时候会转跳到搜索结果的页面底部，关掉插件恢复正常，请排查一下谢谢

**Comment by Lydanne** [comment]
不太明白你的意思,请配图说明

**Comment by LisonChan** [comment]
> 不太明白你的意思,请配图说明

在Google搜索页面，比如我搜索“联想”：
<img width="1377" alt="截屏2020-04-30 下午12 49 29" src="https://user-images.githubusercontent.com/38126452/80673184-3afaa180-8ae1-11ea-9fbc-7f7fd07a93a6.png">
点击搜索后到达搜索结果页面时会自动转跳到当前页面的底部：
<img width="1392" alt="截屏2020-04-30 下午12 49 43" src="https://user-images.githubusercontent.com/38126452/80673246-61204180-8ae1-11ea-87db-9cd6cc171822.png">
正常情况应该是在结果页面的顶部
不知能否理解

**Comment by Lydanne** [comment]
这个应该不是该插件的原因,因为该插件没有类似于控制滚动条或者锚点定位的代码

**Comment by LisonChan** [comment]
> 这个应该不是该插件的原因,因为该插件没有类似于控制滚动条或者锚点定位的代码

我也怀疑过，但是我关闭插件之后就没问题了，电脑甚至也重装过，还是会出现这个问题；我还试过其他的翻译也不会出现这个问题
